matrix:
    include:
        - os: osx
          osx_image: xcode7.3
          language: cpp
          compiler:
              - clang
        - os: linux
          dist: trusty
          sudo: false
          language: python
          python: "3.6"
          addons:
              apt:
                  packages:
                      - libc++-dev
                      - libc++abi-dev
                      - uuid-dev

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
             brew update &> /dev/null
          && travis_wait brew install --force-bottle conan
          && conan config install https://vuo.org/sites/default/files/conan-macos.zip
      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
             pip install conan
          && conan config install https://vuo.org/sites/default/files/conan-linux.zip
      ; fi

install:
    - conan user

script:
    - conan create . vuo/stable
      && conan upload --remote vuo --all --confirm zeromq/*
